export const ALL_PROPERTIES= 'ALL_PROPERTIES'
export const ALL_PROPERTIES_SUCCESS = 'ALL_PROPERTIES_SUCCESS' 

export const PROPERTY_BY_ID = 'PROPERTY_BY_ID'
export const PROPERTY_BY_ID_SUCCESS = 'PROPERTY_BY_ID_SUCCESS'

export const ADD_PROPERTY= 'ADD_PROPERTY'
export const ADD_PROPERTY_SUCCESS = 'ADD_PROPERTY_SUCCESS'

export const UPDATE_PROPERTY = 'UPDATE_JOB'
export const UPDATE_PROPERTY_SUCCESS = 'UPDATE_PROPERTY_SUCCESS'

export const REMOVE_PROPERTY= 'REMOVE_PROPERTY'
export const REMOVE_PROPERTY_SUCCESS = 'REMOVE_PROPERTY_SUCCESS'


export const ALL_CLIENTS= 'ALL_CLIENTS'
export const ALL_CLIENTS_SUCCESS = 'ALL_CLIENTS_SUCCESS' 

export const CLIENT_BY_ID = 'CLIENT_BY_ID'
export const CLIENT_BY_ID_SUCCESS = 'CLIENT_BY_ID_SUCCESS'

export const ADD_CLIENT = 'ADD_CLIENT'
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS'

export const UPDATE_CLIENT = 'UPDATE_CLIENT'
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS'
  
export const  ALL_CLIENT_LEASES= 'ALL_CLIENT_LEASES'
export const  ALL_CLIENT_LEASES_SUCCESS = 'ALL_CLIENT_LEASES_SUCCESS'

export const SINGLE_CLIENT_LEASES ='SINGLE_CLIENT_LEASES'
export const SINGLE_CLIENT_LEASES_SUCCESS ='SINGLE_CLIENT_LEASES_SUCCESS'


export const ALL_OWNERS= 'ALL_OWNERS'
export const ALL_OWNERS_SUCCESS = 'ALL_OWNERS_SUCCESS' 

export const OWNER_BY_ID = 'OWNER_BY_ID'
export const OWNER_BY_ID_SUCCESS = 'OWNER_BY_ID_SUCCESS'

export const ADD_OWNER = 'ADD_OWNER'
export const ADD_OWNER_SUCCESS = 'ADD_OWNER_SUCCESS'

export const UPDATE_OWNER = 'UPDATE_OWNER'
export const UPDATE_OWNER_SUCCESS = 'UPDATE_OWNER_SUCCESS'
  
export const ALL_OWNERS_PROPERTIES= 'ALL_OWNERS_PROPERTIES'
export const ALL_OWNERS_PROPERTIES_SUCCESS = 'ALL_OWNERS_PROPERTIES_SUCCESS'

export const SINGLE_OWNER_PROPERTY= 'SINGLE_OWNER_PROPERTY'
export const SINGLE_OWNER_PROPERTY_SUCCESS = 'SINGLE_OWNER_PROPERTY_SUCCESS'

export const SINGLE_OWNERS_LEASES ='SINGLE_OWNERS_LEASES'
export const SINGLE_OWNER_LEASES_SUCCESS =' SINGLE_OWNER_LEASES_SUCCESS'

export const ALL_OWNERS_LEASES ='ALL_OWNERS_LEASES'
export const ALL_OWNER_LEASES_SUCCESS ='ALL_OWNER_LEASES_SUCCESS'

export const ADMIN_BY_ID = 'ADMIN_BY_ID'
export const ADMIN_BY_ID_SUCCESS = 'ADMIN_BY_ID_SUCCESS'

export const ADD_ADMIN = 'ADD_ADMIN'
export const ADD_ADMIN_SUCCESS = 'ADD_ADMIN_SUCCESS'

export const UPDATE_ADMIN= 'UPDATE_ADMIN'
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS'

